### ISSUE TITLE
1.0 release (feedback desired)

### ISSUE THREAD

**Issue by barrucadu** [barrucadu/irc-client#24]
I'm planning on fixing #12, #20, #21, #22, #23, and releasing version ~~0.5~~1.0.

In the process of working on #23, I found myself wondering just what things need to be exposed. Specifically, do any lenses for `ConnectionConfig` need to be exposed *at all*? In [yukibot](https://github.com/barrucadu/yukibot) I never modify the `ConnectionConfig` after creation, and creation lets you set all the fields it makes sense to set. To check I haven't missed anything, I'd appreciate it if anyone who *does* modify `ConnectionConfig` after calling one of the `connect*` functions could let me know: @siers, @JanGe.

Also, any other feature requests for ~~0.5~~1.0, let me know.

**Comment by JanGe** [comment]
Hey @barrucadu, thanks for the ping.

I'm also only changing the `ondisconnect` and `onconnect` hooks:

```
    conn <- connectWith logger network (fromIntegral remotePort) 1
    IRC.startStateful (connConfig conn hooks) (ircConfig hooks) initState
  where
    [...]
    connConfig conn' hooks' = conn'
        { IRC._onconnect    = IRC.defaultOnConnect    >> mapM_ onConnect    hooks'
        , IRC._ondisconnect = IRC.defaultOnDisconnect >> mapM_ onDisconnect hooks'
        }
    connectWith
        | useSecure = IRC.connectWithTLS'
        | otherwise = IRC.connect'
```

The only issue I had with `irc-client` is that accessing and managing the user state is a bit cumbersome. But I'm also not sure how that could be improved. I might write down a proposal, if I manage to find some time to think about it.

**Comment by siers** [comment]
Good morning,

I am changing the connectionConfig only for `onconnect`/`ondisconnect` too.

Regarding user state: I had implemented my own get/set state with `liftIO $ atomically . get/setTVar`, but then I wanted to modify and it got me thinking about lenses, so I came up with this:

I implemented my bot as a `newtype Bot a = StatefulIRC MyBotsState a`[Zn/Bot.hs:54](https://github.com/siers/zn/blob/master/Zn/Bot.hs#L54), so that I could make a `MonadState` instance for it [Zn/Bot.hs:58](https://github.com/siers/zn/blob/master/Zn/Bot.hs#L58) and therefore use it easily [Zn/Bot.hs:87](https://github.com/siers/zn/blob/master/Zn/Bot.hs#L87), [Zn/Commands/Logs.hs:33](https://github.com/siers/zn/blob/master/Zn/Commands/Logs.hs#L33) like that.

Would this approach make using user state easier for you @JanGe?

**Comment by JanGe** [comment]
@siers I also defined a `newtype` for `StatefulIRC`, but didn't think of making it an instance of `MonadState`. Should definitely work for me and remove a lot of boilerplate. Thanks for the hint!

**Comment by barrucadu** [comment]
I like that `MonadState` idea.

**Comment by Profpatsch** [comment]
There’s a lot of changes happening right now and my (arguably simple) bot doesn’t compile any more. Will test the new interface once it has stabilized.

**Comment by barrucadu** [comment]
Hmm, that's a good point. Things have changed a lot. Maybe I should bump the version to 1.0 rather than 0.5.
